-- SYSTEM계정
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER MUSTHAVE IDENTIFIED BY 1234;

-- 권한부여시 테이블 스페이스 권한을 추가로 부여해야한다.
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO MUSTHAVE; 

SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM DBA_TABLESPACES;

SELECT TABLESPACE_NAME, SUM(BYTES), MAX(BYTES) 
FROM DBA_FREE_SPACE
GROUP BY TABLESPACE_NAME;

-- 개인 계정이 어느 테이블 스페이스에 들어 있는지 확인
SELECT USERNAME, DEFAULT_TABLESPACE
FROM DBA_USERS
WHERE USERNAME 
IN UPPER('MUSTHAVE');

ALTER USER MUSTHAVE QUOTA 5M ON USERS;

-- MUSTHAVE 


